// ─────────────────────────────────────────────────────────────────────────────
// NOTE: All "Cannot find module" errors below are pre-install.
// Run `npm install` once and they all disappear.
// ─────────────────────────────────────────────────────────────────────────────
import { App } from '@slack/bolt';
import Anthropic from '@anthropic-ai/sdk';
import 'dotenv/config';
import { runAgentLoop } from '../agent/loop';
import repoConfig from '../agent/repos.config.json';

// ── Validation ────────────────────────────────────────────────────────────────
const REQUIRED_ENV = ['SLACK_BOT_TOKEN', 'SLACK_APP_TOKEN', 'ANTHROPIC_API_KEY'];
for (const key of REQUIRED_ENV) {
  if (!process.env[key]) {
    console.error(`Missing required environment variable: ${key}`);
    process.exit(1);
  }
}

// ── Slack App (Socket Mode — no public URL required) ──────────────────────────
const app = new App({
  token: process.env.SLACK_BOT_TOKEN!,
  appToken: process.env.SLACK_APP_TOKEN!,
  socketMode: true,
});

// ── Claude client (reads ANTHROPIC_API_KEY from env automatically) ────────────
const claude = new Anthropic();

const MODEL = 'claude-sonnet-4-20250514';
const repoAliases = Object.keys(repoConfig.repos) as Array<keyof typeof repoConfig.repos>;

// ── Intent types ──────────────────────────────────────────────────────────────
interface ParsedIntent {
  repo: string;
  service: string | null;
  taskType: 'feature' | 'bugfix' | 'refactor' | 'test' | 'other';
  /** Short kebab-case label — reserved for future branch naming (max 50 chars) */
  description: string;
  /** Full task instruction forwarded to the agent loop */
  fullTask: string;
}

// ── Intent parser — separate Claude call with tight JSON schema ───────────────
async function parseIntent(userMessage: string): Promise<ParsedIntent | null> {
  const serviceMap = Object.fromEntries(
    repoAliases.map((alias) => [alias, repoConfig.repos[alias].services ?? []])
  );

  const res = await claude.messages.create({
    model: MODEL,
    max_tokens: 600,
    system: [
      'You are a strict intent-parsing assistant for a multi-repo engineering bot.',
      '',
      `Available repos: ${repoAliases.join(', ')}`,
      `Services per repo: ${JSON.stringify(serviceMap, null, 2)}`,
      '',
      'Extract a JSON object from the user message.',
      'Respond with ONLY valid JSON — no markdown, no backticks, no explanation.',
      'Schema:',
      '{',
      '  "repo": string,          // must match one of the available repos exactly, or null if unclear',
      '  "service": string|null,  // must match a service in that repo exactly, or null',
      '  "taskType": "feature"|"bugfix"|"refactor"|"test"|"other",',
      '  "description": string,   // max 50 chars, kebab-case, suitable for a git branch name',
      '  "fullTask": string       // the full task instruction for the AI agent',
      '}',
      '',
      'If you cannot determine the repo, set repo to null.',
      'If you cannot determine the service, set service to null.',
    ].join('\n'),
    messages: [{ role: 'user', content: userMessage }],
  });

  try {
    // Typed without relying on the package being installed — safe pre and post npm install
    const content = res.content as Array<{ type: string; text?: string }>;
    const textBlock = content.find((block) => block.type === 'text');
    if (!textBlock?.text) return null;

    const intent = JSON.parse(textBlock.text!) as ParsedIntent;
    if (!intent.repo || !(repoAliases as string[]).includes(intent.repo)) return null;
    return intent;
  } catch {
    return null;
  }
}

// ── Git workflow ──────────────────────────────────────────────────────────────
// TODO (Phase 2): Auto-commit and push to git.surfboard.se (GitLab).
// The function body is ready — just uncomment this block and the call-sites below
// once the git phase is approved.
//
// async function commitAndPushBranch(
//   repoAlias: keyof typeof repoConfig.repos,
//   intent: ParsedIntent
// ): Promise<string> {
//   import { execSync } from 'child_process';   ← move to top-level import when enabling
//
//   const repoPath = repoConfig.repos[repoAlias].path;
//   const serviceSlug = intent.service ? `${intent.service}-` : '';
//   const branch = `agent/${serviceSlug}${intent.description}-${Date.now()}`;
//
//   try {
//     const status = execSync('git status --porcelain', { cwd: repoPath }).toString().trim();
//     if (!status) return '📭 No file changes detected — nothing to commit.';
//
//     execSync(`git checkout -b ${branch}`, { cwd: repoPath });
//     execSync('git add -A', { cwd: repoPath });
//     execSync(
//       `git commit -m "${intent.taskType}(${intent.service ?? repoAlias}): ${intent.description}\n\nAuto-generated by Claude Agent\nTask: ${intent.fullTask.slice(0, 200)}"`,
//       { cwd: repoPath }
//     );
//     execSync(`git push origin ${branch}`, { cwd: repoPath });
//
//     const remote = repoConfig.repos[repoAlias].gitRemote;
//     const repoSlug = remote.replace('git@git.surfboard.se:', '').replace('.git', '');
//
//     return [
//       `📦 Branch pushed: \`${branch}\``,
//       `🔗 Open MR at: https://git.surfboard.se/${repoSlug}/-/merge_requests/new?merge_request[source_branch]=${branch}`,
//       `*(git.surfboard.se is GitLab — gh CLI does not apply)*`,
//     ].join('\n');
//   } catch (err) {
//     return `⚠️ Git error: ${String(err)}`;
//   }
// }

// ── Slack message handler ─────────────────────────────────────────────────────
// Using `any` on the handler args is intentional pre-install: @slack/bolt types
// are not resolved until `npm install` runs. After install, the destructured
// params (message, say, client) are fully typed by @slack/bolt's own generics.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
app.message(async ({ message, say, client: slackClient }: any) => {
  // Ignore bot messages, edits, and message_changed/message_deleted subtypes
  if (message.subtype) return;
  if (!message.text) return;
  // Only respond to top-level messages, not thread replies
  if (message.thread_ts && message.thread_ts !== message.ts) return;

  const threadTs: string = message.ts;
  const channelId: string = message.channel;

  // 1. Acknowledge immediately
  await say({ text: '🔍 Parsing your request...', thread_ts: threadTs });

  // 2. Parse intent
  let intent: ParsedIntent | null;
  try {
    intent = await parseIntent(message.text as string);
  } catch (err) {
    await say({ text: `❌ Intent parsing failed: ${String(err)}`, thread_ts: threadTs });
    return;
  }

  if (!intent) {
    await say({
      text: [
        '❌ Could not determine the target repo from your message.',
        '',
        `*Available repos:* \`${repoAliases.join('`, `')}\``,
        '',
        '*Example requests:*',
        '• _"In the services repo, add a health endpoint to merchant-service"_',
        '• _"Fix the null-check bug in terminal repo datecs-acquiring service"_',
        '• _"Refactor swells payment-isolate to extract validateOrder into utils"_',
      ].join('\n'),
      thread_ts: threadTs,
    });
    return;
  }

  // 3. Confirm understanding
  await say({
    text: [
      '✅ *Task understood*',
      `• Repo: \`${intent.repo}\``,
      `• Service: \`${intent.service ?? 'N/A (repo-wide)'}\``,
      `• Type: \`${intent.taskType}\``,
      '',
      `📋 *Task:* ${intent.fullTask}`,
      '',
      '⚙️ Starting agent...',
    ].join('\n'),
    thread_ts: threadTs,
  });

  // 4. Run agent loop — streams live tool-call updates into the Slack thread
  const progressCallback = async (update: string): Promise<void> => {
    await slackClient.chat.postMessage({
      channel: channelId,
      thread_ts: threadTs,
      text: update,
      mrkdwn: true,
    });
  };

  let agentResult: string;
  try {
    agentResult = await runAgentLoop(
      intent.repo,
      intent.fullTask,
      intent.service ?? undefined,
      progressCallback
    );
  } catch (err) {
    await say({ text: `❌ *Agent error*: ${String(err)}`, thread_ts: threadTs });
    return;
  }

  // 5. Final summary
  // NOTE: Git commit/push (Phase 2) will go here once enabled.
  // Replace the block below with commitAndPushBranch() when Phase 2 lands.
  await say({
    text: [
      '✅ *Task Complete*',
      '',
      agentResult,
      '',
      '---',
      '📝 *Next step (manual for now)*: review the changes in the repo, then commit & push.',
    ].join('\n'),
    thread_ts: threadTs,
    mrkdwn: true,
  });
});

// ── Start ─────────────────────────────────────────────────────────────────────
(async () => {
  await app.start();
  console.log('⚡ Claude Agent Bot is running (Socket Mode)');
  console.log(`📦 Registered repos: ${repoAliases.join(', ')}`);
  console.log(`🤖 Model: ${MODEL}`);
  console.log('📡 Git host: git.surfboard.se (GitLab — Phase 2 will auto-push branches)');
})();
